spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.frontend.origin=https://twoj-front.pl

payu.client-id=${PAYU_CLIENT_ID}
payu.client-secret=${PAYU_CLIENT_SECRET}
payu.auth-url=${PAYU_AUTH_URL}
payu.order-url=${PAYU_ORDER_URL}

logging.level.org.springframework=INFO
logging.level.com.artshop=INFO
