spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.security.admin.username=${APP_SECURITY_ADMIN_USERNAME}
app.security.admin.password-hash=${APP_SECURITY_ADMIN_PASSWORD_HASH}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.exp-minutes=${APP_JWT_EXP_MINUTES:120}

# PayU z ENV (dev.env) ? sandbox/credentials
payu.client-id=${PAYU_CLIENT_ID}
payu.client-secret=${PAYU_CLIENT_SECRET}
payu.auth-url=${PAYU_AUTH_URL}
payu.order-url=${PAYU_ORDER_URL}
payu.continue-url=${PAYU_CONTINUE_URL}
payu.notify-url=${PAYU_NOTIFY_URL}

#Mail
app.mail.toAddress1=${APP_MAIL_TOADDRESS1}
app.mail.toAddress2=${APP_MAIL_TOADDRESS2}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS}

logging.level.org.springframework=INFO
logging.level.com.artshop=INFO

server.forward-headers-strategy=framework